name: Run Stocks of interest

on:
  schedule:
    - cron: "0 2 * * 1-5"   # 台灣時間 10:00（UTC+8 → UTC 02:00）
    - cron: "0 5 * * 1-5"   # 台灣時間 13:00（UTC+8 → UTC 05:00）
  workflow_dispatch:

jobs:
  run-watchers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run MA20 Watcher
        run: python interest_watcher_ma20.py
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}

      - name: Run KD+MACD Watcher
        run: python interest_KD_MACD.py
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
